version: '3.8'

services:
  mariadb:
    container_name: IKREFACT_BOUNCER-mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: TotallyHackable
      MARIADB_DATABASE: Bouncer
    ports:
      - "3306:3306"
